<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>winexe</OutputType>
    <UseWindowsForms>true</UseWindowsForms>
    <TargetFramework>net9.0-windows</TargetFramework>
    <EnableUnsafeBinaryFormatterSerialization>true</EnableUnsafeBinaryFormatterSerialization>
    <NoWarn>NU1701</NoWarn>
  </PropertyGroup>

  <PropertyGroup>
    <DebugType>embedded</DebugType>
    <PublishSingleFile>true</PublishSingleFile>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="res\**" CopyToPublishDirectory="PreserveNewest"/>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NAudio.Lame" Version="1.1.5" />
    <PackageReference Include="SharpDX.D3DCompiler" Version="4.2.0" />
    <PackageReference Include="SharpDX.Desktop" Version="4.2.0" />
    <PackageReference Include="SharpDX.Direct2D1" Version="4.2.0" />
    <PackageReference Include="SharpDX.Direct3D11" Version="4.2.0" />
    <PackageReference Include="SharpDX.Mathematics" Version="4.2.0" />
    <PackageReference Include="System.Runtime.Serialization.Formatters" Version="9.0.0" />
  </ItemGroup>

</Project>